# services
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment the line below if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./runtime/data:/data
      - ./runtime/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db

  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./runtime/mysql:/var/lib/mysql

  redis:
    image: docker.io/library/redis:alpine
    container_name: oauth2-redis
    command: --save 60 1 --loglevel warning
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./runtime/oauth2/redis:/data

  oauth2proxy:
    # internal: oauth2proxy on port 4180
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2proxy
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_REVERSE_PROXY: true
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: 5m
      #OAUTH2_PROXY_SCOPE: user:email
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: false
      OAUTH2_PROXY_PASS_USER_HEADERS: true
      OAUTH2_PROXY_SET_XAUTHREQUEST: true
      #Cookies
      OAUTH2_PROXY_COOKIE_name: "auth_creekside"
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_COOKIE_EXPIRE: "2h"
      ## cookie storage at local redis
      OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
      OAUTH2_PROXY_REDIS_CONNECTION_URL: "redis://redis:6379"

      OAUTH2_PROXY_COOKIE_SECRET: '*****'
      # Required so cookie can be read on all subdomains.
      OAUTH2_PROXY_COOKIE_DOMAINS: '.creekside.network'
      # Required to allow redirection back to original requested target.
      OAUTH2_PROXY_WHITELIST_DOMAINS: '.creekside.network'
      # Azure
      OAUTH2_PROXY_PROVIDER: 'azure'
      OAUTH2_PROXY_CLIENT_ID: 'xxxxx'
      OAUTH2_PROXY_CLIENT_SECRET: '*****'
      OAUTH2_PROXY_EMAIL_DOMAINS: 'creekside.network, creeksidepro.mail.onmicrosoft.com'
      OAUTH2_PROXY_AZURE_TENANT: 'zzzzz'
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://login.microsoftonline.com/zzzzz/v2.0'
      OAUTH2_PROXY_REDIRECT_URL: 'https://auth.creekside.network/oauth2/callback'
      # Customize
      OAUTH2_PROXY_BANNER: "Creekside Oauth2 Proxy Portal"
      OAUTH2_PROXY_FOOTER: "Powered by Creekside Networks 2019-2025"
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: true
    depends_on:
      - npm-app
      - redis
    restart: always

   